### ISSUE TITLE
cannot build without thread API

### ISSUE THREAD

**Issue by pca006132** [NVIDIA/thrust#1902] opened 2023-03-23 10:54 UTC
Hi, we use thrust in https://github.com/elalish/manifold and we want to support both native and WASM execution. We currently uses CUDA and TBB/OMP for native execution and CPP backend (serial) for WASM.

When trying to [upgrade to the latest 2.1 release](https://github.com/elalish/manifold/pull/389), we found that the new dependency libcudacxx requires thread API to build. It would be nice if we can build without using the thread API, considering we are not using multithreading for those builds.

**Comment by elalish** [comment] 2023-03-28 17:26
This is looking more like a blocker, since even when enabling `-pthread` in emscripten, we still get Thrust's `No Thread API` error. So perhaps there is an additional bug regarding detecting pthread support in the emscripten compiler? 

Still, considering all the [complexities](https://emscripten.org/docs/porting/pthreads.html#special-considerations) of using pthreads in WASM, especially since we require `ALLOW_MEMORY_GROWTH`, the better option would still be to simply not require the thread API at all for the serial backend.

**Comment by brycelelbach** [comment] 2023-03-29 11:51
I think this actually an issue with https://github.com/NVIDIA/libcudacxx, not Thrust.

**Comment by brycelelbach** [comment] 2023-03-29 11:52
Can you send us the specific compilation error you're getting?

Can you try defining `-D_LIBCUDACXX_HAS_NO_THREADS` and see if that helps?

**Comment by elalish** [comment] 2023-03-30 15:36
The original error:

/Users/elalish/Code/manifold/src/third_party/thrust/dependencies/libcudacxx/include/cuda/std/detail/libcxx/include/__config:1559:6: error: "No thread API"

With your define I get:

/Users/elalish/Code/manifold/src/third_party/thrust/dependencies/libcudacxx/include/cuda/std/detail/libcxx/include/__config:1584:2: error: _LIBCUDACXX_HAS_NO_THREADS cannot be set when `__STDCPP_THREADS__` is set.

The compile command the generates the error is:

/opt/homebrew/Cellar/emscripten/3.1.31/libexec/em++  @CMakeFiles/collider.dir/includes_CXX.rsp -O3 -DNDEBUG -Werror -Wall -Wno-sign-compare -Wno-unused -fexceptions -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CPP -std=gnu++17 -MD -MT src/collider/CMakeFiles/collider.dir/src/collider.cpp.o -MF CMakeFiles/collider.dir/src/collider.cpp.o.d -o CMakeFiles/collider.dir/src/collider.cpp.o -c /Users/elalish/Code/manifold/src/collider/src/collider.cpp

**Comment by brycelelbach** [comment] 2023-03-30 19:34
Okay give this a shot please: `-D_LIBCUDACXX_HAS_THREAD_API_EXTERNAL -D_LIBCUDACXX_HAS_THREAD_API_CUDA`

**Comment by elalish** [comment] 2023-03-30 20:40
Excellent, that worked! Thank you. Quite the magical incantation.

**Comment by brycelelbach** [comment] 2023-03-30 21:35
Is there a macro that Emscripten defines that we can use to detect the Emscripten environment? If so, then we can do this automatically.

**Comment by elalish** [comment] 2023-03-30 22:59
Looks like it's `__EMSCRIPTEN__`: https://emscripten.org/docs/compiling/Building-Projects.html#detecting-emscripten-in-preprocessor

**Comment by brycelelbach** [comment] 2023-03-30 23:29
I've created a PR to fix this in libcu++. Can you confirm that the issue is fixed once you define those two macros? Nothing else blows up?

**Comment by elalish** [comment] 2023-03-31 00:12
Our tests are now passing our CI on a bunch of different systems, so I think it's good. We just added those defines for the emscripten build.

**Closed** 2023-03-31 07:00 UTC
