### ISSUE TITLE
call to is_sorted does not compile with -gencode flag and separate compilation enabled

### ISSUE THREAD

**Issue by har0ke** [NVIDIA/thrust#1280] opened 2020-09-18 09:18 UTC
A trivial call to `is_sorted` produces the following compilation error:
 `usr/local/cuda-10.2/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/cub/device/dispatch/dispatch_reduce.cuh(446): error: cannot pass an argument with a user-provided copy-constructor to a device-side kernel launch`

Minimal example:
```
#include <thrust/iterator/counting_iterator.h>
#include <thrust/sort.h>

int main() {
    auto zero = thrust::make_counting_iterator(0UL);
    return thrust::is_sorted(zero, zero + 100);
}
```

The issue only persists if `-gencode arch=compute_XX,code=sm_XX` and `-dc` (separate compilation) are both set. I could reproduce the issue on two different machines with with `sm_61` and `sm_75` respectively.

Full nvcc command produced by my cmake configuration:
 `/usr/local/cuda-10.2/bin/nvcc -forward-unknown-to-host-compiler   -gencode arch=compute_75,code=sm_75 -g   -std=c++11 -x cu -dc /home/oke/CLionProjects/scantest/main.cu -o CMakeFiles/scantest.dir/main.cu.o `

-------

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by allisonvacanti** [comment] 2020-10-04 17:45
I can reproduce this with CTK 10.2 (thrust version 1.9.7) but not when I use any version of Thrust newer than 1.9.9 with the same toolchain.

Looks like we fixed this a little while ago. Closing, feel free to reopen if you notice this on a more recent version of Thrust.

**Closed by allisonvacanti** 2020-10-04 17:45 UTC
Labels: info needed
