### ISSUE TITLE
thrust::system::cuda::detail::deallocation_fn type mismatch with cudaFree

### ISSUE THREAD

**Issue by Mochimazui** [NVIDIA/thrust#1458] opened 2021-06-09 07:39 UTC
Using VS2019 Version 16.10.1 and thurst code from CUDA 11.3.1 installation.

Build failes on "thrust/system/cuda/memory_resource.h:87" with error ```a value of type "cudaError_t (*)(void *)" cannot be used to initialize an entity of type "deallocation_fn"```

```c++
typedef detail::cuda_memory_resource<cudaMalloc, cudaFree,
        thrust::cuda::pointer<void> >
        device_memory_resource;
```

cudaFree type is  ```enum cudaError (__stdcall*)(void *)``` but deallocation_fn type is ```enum cudaError (__cdecl*)(void *)```.

Seems we need add __stdcall to deallocation_fn, or modify cuda_memory_resource template to allow both __cdecl and __stcall function pointer here.

Code:

```c++
#include <cstdio>
#include <typeinfo>

#include <cuda.h>
#include <cuda_runtime.h>
#include <driver_types.h>

#include <thrust/device_vector.h>

int main()
{
    thrust::device_vector<int> a;

    printf("cudaFree: %s\n", typeid(cudaFree).name());
    printf("&cudaFree: %s\n", typeid(&cudaFree).name());

    typedef cudaError_t(* deallocation_fn_0)(void*);
    printf("deallocation_fn: %s\n", typeid(deallocation_fn_0).name());

    typedef cudaError_t(__stdcall * deallocation_fn_1)(void*);
    printf("fixed deallocation_fn: %s\n", typeid(deallocation_fn_1).name());
    
    return 0;
}
```

**Comment by allisonvacanti** [comment] 2021-06-18 17:38
@Mochimazui What flags are you using? I built and ran the snippet above, but everything looks ok with our build system:

```
cudaFree: enum cudaError __cdecl(void * __ptr64)
&cudaFree: enum cudaError (__cdecl*)(void * __ptr64)
deallocation_fn: enum cudaError (__cdecl*)(void * __ptr64)
fixed deallocation_fn: enum cudaError (__cdecl*)(void * __ptr64)
```

**Comment by allisonvacanti** [comment] 2021-08-17 17:38
Closing, cannot reproduce. Please reopen with more info if this is still needed.

**Comment by ojakubcik** [comment] 2021-08-19 13:11
This happens when CUDA is used by 32-bit build. In 64-bit build, `__stdcall` is accepted and ignored by compiler, but in 32-bit it is enforced. `cudaMalloc` and `cudaFree` are defined with `CUDARTAPI` macro, which in MSVC environment expands to `__stdcall`.

Thus, the fix (for 32-bit compatible usage) should be:

    typedef cudaError_t (CUDARTAPI *allocation_fn)(void**, std::size_t);
    typedef cudaError_t (CUDARTAPI *deallocation_fn)(void *);

**Comment by allisonvacanti** [comment] 2021-09-13 18:52
Thanks for the info -- reopening.

**Comment by allisonvacanti** [comment] 2021-12-16 17:29
@Mochimazui @ojakubcik #1582 should fix this.

**Closed** 2021-12-17 17:36 UTC
Labels: bug: functional, P1: should have, repro: verified
