### ISSUE TITLE
Inclusive scan doesn't compile with CUDA 11.2

### ISSUE THREAD

**Issue by ibaned** [NVIDIA/thrust#1332] opened 2020-10-28 17:37 UTC
The attached code fails to compile against the Thrust included with CUDA 11.2:
```cpp
#include <iostream>
#include <cstdint>
#include <cuda_runtime_api.h>
#include <cuda.h>
#include <thrust/execution_policy.h>
#include <thrust/transform_scan.h>

typedef std::int32_t LO;

int main() {

  LO *a;

  LO a_h[10] = {5,0,5,8,6,7,5,3,0,9};

  auto err = cudaMalloc(&a, 10);
  std::cout << err << std::endl;
  cudaMemcpy(a, a_h, 10, cudaMemcpyHostToDevice);

  thrust::maximum<LO> binary_op;
  thrust::identity<LO> unary_op;

  thrust::transform_inclusive_scan(thrust::device, a, a+10, a,
      unary_op, binary_op);

  cudaMemcpy(a_h, a, 10, cudaMemcpyDeviceToHost);

  for (int i=0; i<10; i++) std::cout << a_h[i] << "," ;
  std::cout << std::endl;
  cudaFree(a);
  return 0;
}
```

**Comment by allisonvacanti** [comment] 2020-10-28 19:15
Can confirm that this worked in 1.9.10-1: https://www.godbolt.org/z/3o4ffn

It broke in 1.10.0 (slated for 11.2): https://www.godbolt.org/z/Mvseb5

And is still broken in `main`: https://www.godbolt.org/z/odPn8q

We'll need to dig in to figure out what changed. I'm curious if this will be fixed after #1304 is merged, which changes in the implementation of thrust's scans to use `cub::DeviceScan` instead of a custom implementation.

**Comment by ibaned** [comment] 2020-10-28 19:30
@allisonvacanti thank you for promptly looking into this! I support the idea of just calling CUB's device scan directly, so if #1304 or equivalent gets merged before CUDA 11.2 is released officially, and fixes our issue, that solution is fine with us.

**Comment by allisonvacanti** [comment] 2020-10-28 20:06
CUDA 11.2 will be using the 1.10.0 release, and unfortunately it is too late to make changes, so it'll ship with this bug.

I'll see if I can find a workaround when I have time to dig into this a little deeper.

**Comment by ibaned** [comment] 2020-10-28 20:30
Can we also make something similar into a test for Thrust that gets compiled and run prior to shipping a release? I'm not sure what makes it special but maybe it is using raw pointers as iterators? Anyways testing this for `transform_inclusive_scan` and `sort_by_key` would be helpful for our applications.

**Comment by allisonvacanti** [comment] 2020-10-28 21:23
👍 I will definitely be adding a regression test once we get this figured out.

**Comment by allisonvacanti** [comment] 2020-11-06 21:04
#1337 will fix the issue, but unfortunately I don't see an easy workaround for user code.

> testing this for `transform_inclusive_scan` and `sort_by_key` would be helpful for our applications.

A regression test has been added that covers `transform_inclusive_scan` and `transform_exclusive_scan`. `sort_by_key` wouldn't be affected by the root cause of this issue, so all should be well there.

**Comment by ibaned** [comment] 2020-11-09 15:26
@allisonvacanti thanks for the fix and the regression test!

I interpret the lack of an easy workaround to mean that `transform_inclusive_scan` really isn't usable in CUDA 11.2? In that case our team will avoid that version and wait for CUDA 11.3.

Please feel free to close this, a fix and regression test resolves it for us.

**Comment by allisonvacanti** [comment] 2020-11-09 17:36
> I interpret the lack of an easy workaround to mean that transform_inclusive_scan really isn't usable in CUDA 11.2? In that case our team will avoid that version and wait for CUDA 11.3.

This is correct. Alternatively, some projects have started using git submodules/CMake's `add_subdirectory`/CMake Package Manager to use newer versions of Thrust/CUB with their projects. Due to the time it takes to spin up a CUDA release, the CUDA Toolkit will be lagging about a release behind Thrust/CUB going forward, so if you want fast fixes this may be a good option for your project.

You may be able to play with the functors you're using with `transform_inclusive_scan` on the broken versions of thrust. I noticed that this error would happen for some functors (e.g. `thrust::identity<>`) but not others (e.g. `thrust::negate<>`). I didn't spend a lot of time looking into why, but this point towards a workaround for your specific usecase.

**Comment by ibaned** [comment] 2020-11-09 17:41
Thanks! We can try both of those suggestions

**Closed** 2020-11-11 19:21 UTC
Labels: P0, functional bug
