### ISSUE TITLE
Too many comparisions during calling to `thrust::sort` and `thrust::stable_sort`

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/thrust#1436] opened 2021-05-17 19:47 UTC
Please consider the following code snippet:
```
struct counter {
  int* count_ptr;
  __device__ bool operator()(int i, int j) noexcept
  {
    atomicAdd(count_ptr, 1);
    return i < j;
  }
};

rmm::device_uvector<int> indices(2, stream);
thrust::sequence(rmm::exec_policy(stream), indices.begin(), indices.end(), 0);

auto count = cudf::detail::make_zeroed_device_uvector_async<int>(1, stream);
counter _counter{count.begin()};
thrust::sort(rmm::exec_policy(stream), indices.begin(), indices.end(), _counter);

int tmp;
CUDA_TRY(
cudaMemcpyAsync(&tmp, count.begin(), sizeof(int), cudaMemcpyDeviceToHost, stream.value()));
stream.synchronize();

printf("Num. comparisons: %d\n", tmp);
```

In summary, the code above calls `thrust::sort` on a vector of two integer numbers, and counts the number of comparisons. The output of that code is:
```
Num. comparisons: 34817
```

Obviously, such number of comparisons is too excessive when sorting 2 numbers. Since I have only 1 GPU to test (Tesla T4), I don't know if that number is consistent across devices.

I also get the same number of comparisons when using `thrust::stable_sort`.

**Comment by ttnghia** [comment] 2021-05-17 20:34
Below are some other numbers when sorting arrays with different sizes:
2 --- Num. comparisons: 34817
10 --- Num. comparisons: 34825
100 --- Num. comparisons: 35111
1000 --- Num. comparisons: 40475
10000 --- Num. comparisons: 170980
100000 ---

**Comment by ttnghia** [comment] 2021-05-17 21:56
I also tried to count the number of comparisons in different ways. For sorting two numbers as above, here is some insight:

- There is exactly 1 comparison of number at index 0 with number at index 1.
- There are 9 comparisons of number at index 1 with number at index 0.
- There are 34680 comparisons of number at index 0 with itself.
- and remaining 127 comparisons of number at index 1 with itself.

**Comment by senior-zero** [comment] 2021-05-22 15:48
Hello! I've reproduced this behaviour. [Here is the complete source file](https://gist.github.com/senior-zero/0ef1a16bc852fec0141e6d62186f1a54) that I run on RTX3090. The `thrust::sort` actually uses two approaches. If the input data type is arithmetic and the comparator is `thrust::less`, or `thrust::greater` cub radix sort is called. Otherwise, merge sort is called. Because you use the custom comparator, you force thrust to switch to the merge sort. 

Merge sort uses different policies for different architectures. I'm going to explain the numbers I have on RTX3090. In my case, the merge sort allocates 512 threads for the thread block, and each thread processes 15 elements. That gives us a tile of 7680 elements.

In the `ConsumeTile` function, each thread computes the maximal value within the part assigned to it. It leads to `ITEMS_PER_THREAD - 1` comparison for the tile indices within input data size limits. In the example above, we have two input elements. Therefore there is only one comparator call.

Block merge sort itself perform `O(ITEMS_PER_THREAD^2)` comparisons for each thread in the `stable_odd_even_sort` function. That gives us another 53760 comparisons. 

Therefore I have 53761 comparisons before the merge sort main loop. Further logic depends on the values. Consequently, it might increase the comparisons count even further. The problem here is that the last tile contains a lot of threads with no input data. These threads don't need to perform `stable_odd_even_sort`, because their local buffers are filled with some fixed value beforehand. 

I've added some logic so as to skip the `stable_odd_even_sort` call for threads with no input data and got 106 comparisons in total. Here you can see the comparisons count after and before this fix for INT32 input data type. 

![image](https://user-images.githubusercontent.com/9890394/119232279-4cb84800-bb2d-11eb-81d8-499722f724e7.png)

As you can see, two graphs converge as tile filling approaches 100%. The difference between comparisons counts after and before the fix reaches insignificant values when the tile is filled by 10%. 

![image](https://user-images.githubusercontent.com/9890394/119232314-6fe2f780-bb2d-11eb-9ff0-c33c53f47304.png)

Therefore any performance improvements could be observed on relatively small input data sizes. I've measured the speedup of the version with the fix. Even for some complex comparators and small input data sizes, I haven't managed to get a speedup of more than 2% for both INT32 and FP64. 

![image](https://user-images.githubusercontent.com/9890394/119232416-d7994280-bb2d-11eb-90dd-51369e0056ea.png)

Could you tell me:

- Do you have to use a custom comparator with arithmetic types? 
- Does this behaviour cause any performance issue in your case? If so, could you provide an example of a comparator that leads to a significant slowdown due to excessive comparator calls?

**Closed** 2021-06-08 16:36 UTC
Labels: triage
