### ISSUE TITLE
Consider set_intersection_by_key overload which takes two values ranges

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/thrust#353] opened 2013-03-17 07:27 UTC
`set_intersection_by_key` takes a single value input range because the semantics of `set_intersection` are to copy matches from only the first set. The generalization to `set_intersection_by_key` therefore makes an accompanying values range for the second input set meaningless.

However, sometimes what we want is to identify which keys in the second input set were matches or to copy values associated with the matches from the second input set. It doesn't seem like we can do that with the existing API.

We could extend `set_intersection_by_key`'s existing API with these overloads:

```
template<typename InputIterator1,
         typename InputIterator2,
         typename InputIterator3,
         typename InputIterator4,
         typename OutputIterator1,
         typename OutputIterator2,
         typename OutputIterator3>
  thrust::tuple<OutputIterator1,OutputIterator2,OutputIterator3>
    set_intersection_by_key(InputIterator1  keys_first1,
                            InputIterator1  keys_last1,
                            InputIterator2  keys_first2,
                            InputIterator2  keys_last2,
                            InputIterator3  values_first1,
                            InputIterator4  values_first2,
                            OutputIterator1 keys_result,
                            OutputIterator2 values_result1,
                            OutputIterator3 values_result2);

template<typename InputIterator1,
         typename InputIterator2,
         typename InputIterator3,
         typename InputIterator4,
         typename OutputIterator1,
         typename OutputIterator2,
         typename OutputIterator3,
         typename Compare>
  thrust::tuple<OutputIterator1,OutputIterator2,OutputIterator3>
    set_intersection_by_key(InputIterator1  keys_first1,
                            InputIterator1  keys_last1,
                            InputIterator2  keys_first2,
                            InputIterator2  keys_last2,
                            InputIterator3  values_first1,
                            InputIterator4  values_first2,
                            OutputIterator1 keys_result,
                            OutputIterator2 values_result1,
                            OutputIterator3 values_result2,
                            Compare         comp);
```

These additions wouldn't be ambiguous because they have more parameters than all of the existing `set_intersection_by_key` functions.

**Comment by jrhemstad** [comment] 2023-03-07 15:16
Closing as a dupe of https://github.com/NVIDIA/thrust/issues/206

**Closed by jrhemstad** 2023-03-07 15:16 UTC
Labels: type: enhancement, thrust
