### ISSUE TITLE
Inconsistent behavior in thrust::exclusive_scan between cuda 11.1 and cuda 11.2

### ISSUE THREAD

**Issue by xwang233** [NVIDIA/thrust#1379] opened 2021-02-03 18:31 UTC
https://github.com/pytorch/pytorch/issues/51544

THRUST_VERSION

cuda 11.1 is using 100910
cuda 11.2 is using 101000

I have a short repro script, name it "main.cu", and simply compile it with "nvcc main.cu"
 
```cpp
#include <iostream>

#include <thrust/execution_policy.h>
#include <thrust/device_ptr.h>
#include <thrust/scan.h>

// #define mask_t bool
#define mask_t int64_t
#define N 10

#define XSTR(x) STR(x)
#define STR(x) #x

#pragma message "mask_t is " XSTR(mask_t)

int main() {
    mask_t h_data[N];
    mask_t *d_data;
    int64_t *ds_data;
    int64_t hs_data[N];

    cudaMalloc((void**)&d_data, sizeof(mask_t) * N);
    cudaMalloc((void**)&ds_data, sizeof(int64_t) * N);

    for (int i = 0; i < N; i++) {
        h_data[i] = static_cast<mask_t>(i % 2);
        printf("%d ", h_data[i]);
    }
    printf("\n");

    cudaMemcpy(d_data, h_data, sizeof(mask_t) * N, cudaMemcpyHostToDevice);

    thrust::device_ptr<mask_t> td_data(d_data);
    thrust::device_ptr<int64_t> tds_data(ds_data);

    thrust::exclusive_scan(
        td_data,
        td_data + N,
        tds_data
    );

    cudaDeviceSynchronize();

    cudaMemcpy(hs_data, ds_data, sizeof(int64_t) * N, cudaMemcpyDeviceToHost);

    for (int i = 0; i < N; i++) {
        printf("%ld ", hs_data[i]);
    }
    printf("\n");

    cudaFree(d_data);
    cudaFree(ds_data);
}

```

In cuda 11.1, I got

```
(base) root@6a36499d0122:/workspace/thrust-exclusive-scan# make
nvcc main.cu
main.cu(14): remark: #pragma message: "mask_t is bool"

main.cu:14:17: note: #pragma message: mask_t is bool
   14 | #pragma message "mask_t is " XSTR(mask_t)
      |                 ^~~~~~~~~~~~~~~~
./a.out
0 1 0 1 0 1 0 1 0 1
0 0 1 1 2 2 3 3 4 4
(base) root@6a36499d0122:/workspace/thrust-exclusive-scan# vim main.cu
(base) root@6a36499d0122:/workspace/thrust-exclusive-scan# make
nvcc main.cu
main.cu(14): remark: #pragma message: "mask_t is int64_t"

main.cu:14:17: note: #pragma message: mask_t is int64_t
   14 | #pragma message "mask_t is " XSTR(mask_t)
      |                 ^~~~~~~~~~~~~~~~~~~
main.cu: In function ‘int main()’:
main.cu:27:8: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
   27 |         printf("%d ", h_data[i]);
      |        ^~~~~  ~~~~~~~~~
      |                       |
      |                       int64_t {aka long int}
./a.out
0 1 0 1 0 1 0 1 0 1
0 0 1 1 2 2 3 3 4 4
```

In cuda 11.2, I got

```
$ make
nvcc main.cu
main.cu(14): remark: #pragma message: "mask_t is int64_t"

main.cu:14:17: note: ‘#pragma message: mask_t is int64_t’
   14 | #pragma message "mask_t is " XSTR(mask_t)
      |                 ^~~~~~~~~~~~~~~~~~~
./a.out
0 1 0 1 0 1 0 1 0 1
0 0 1 1 2 2 3 3 4 4

$ make
nvcc main.cu
main.cu(14): remark: #pragma message: "mask_t is bool"

main.cu:14:17: note: ‘#pragma message: mask_t is bool’
   14 | #pragma message "mask_t is " XSTR(mask_t)
      |                 ^~~~~~~~~~~~~~~~
./a.out
0 1 0 1 0 1 0 1 0 1
0 0 1 1 1 1 1 1 1 1
```

where the behavior of "mask_t is bool" in cuda 11.2 seems to be inconsistent.

**Comment by xwang233** [comment] 2021-02-03 18:32
cc @ptrblck

**Comment by allisonvacanti** [comment] 2021-02-03 19:20
Thanks for the detailed bug report! This is a known change introduced with #1176.

There's more detail in that PR, but the short version is that mixing scan input/output types is not well defined behavior -- the intermediate accumulator type is not specified by the current C++ standard. There is a proposal to define these edge cases better (https://wg21.link/P0571), and Thrust/CUB recently updated their non-segmented scans to follow this proposal.

The new behavior is well-defined across all implementations in these libraries:
- If the algorithm overload specifies an `InitialValueType`, that type is used for the accumulator.
- Otherwise, the `value_type` of the input iterator is used.

The old behavior can be restored by explicitly specifying an `InitialValueType` for `exclusive_scan`, or by using something like `thrust::transform_iterator` to explicitly cast the input iterators to return the desired `value_type` for `inclusive_scan` (which doesn't have an "initial value" argument).

Closing since this is intended behavior.

**Closed by allisonvacanti** 2021-02-03 19:20 UTC
Labels: wontfix
