### ISSUE TITLE
RuntimeError: radix_sort: failed

### ISSUE THREAD

**Issue by robomike** [NVIDIA/thrust#1535] opened 2021-10-06 22:19 UTC
When investigating this issue, the problem seems to be with thrust https://github.com/cupy/cupy/issues/5846. 

Can you please take a look at let us know why this problem with thurst occurs?

**Comment by elstehle** [comment] 2023-02-24 16:13
Thanks for reporting the issue, @robomike. I assume that the root cause of this issue is related to https://github.com/NVIDIA/cub/issues/545, as there are multiple shared symptoms. I assume that this issue has been addressed by PR https://github.com/NVIDIA/cub/pull/547. So, I will close the issue for now. Please feel free to reopen, should you still experience the issue, @robomike.

**Closed by elstehle** 2023-02-24 16:13 UTC
Labels: type: bug: functional, info needed, repro: missing, thrust
