### ISSUE TITLE
thrust::mt19937 : Is this doable in the future?

### ISSUE THREAD

**Issue by hopingforblessing** [NVIDIA/thrust#895] opened 2017-11-23 09:35 UTC
I am a newbie in CUDA and Thrust, however, I have to say, thrust is so **amazing**. 

I am working on a CUDA accelerated Monte Carlo problem that require at least 10^13 random numbers. MT19937 seems to be a good random number generator but it is not included in Thrust. Is there any plan that Thrust could include this in the next release?

My problem is basically as following:
in Thrust example _monte carlo .cu_ files, (it calculates pi with a transfrom_reduce for aggregation, and the random number is generated on GPU "__device__" function,). I am currently using _cuRand_ but it does not have the MT random number generator on the  "__device__" side.

Thanks!

**Comment by jaredhoberock** [comment] 2017-12-04 20:21
Mersenne Twister is probably not a good fit for parallel applications because its state is relatively large. The PRNGs Thrust currently supports have relatively small state. Moreover, generating the nth state typically requires either O(n) or O(nlgn) sequential steps.

Moving forward, I think a better strategy for PRNG support will be by targeting PRNGs which are specifically designed with parallelism in mind.

**Comment by brycelelbach** [comment] 2018-02-13 02:02
@jaredhoberock should we file this as an RFE for improved device-side PRNGs?

**Comment by jaredhoberock** [comment] 2018-02-13 17:19
It's not really a question of what makes sense on device or host, the issue is that none of the standard random number generators are a good fit for parallelism.

The problem is that when multiple threads use the same PRNG initialized from different seeds, the output may be correlated. A better approach is to have all the different threads use the same random number sequence, but "leap frog" each other when taking samples from the sequence. Such an arrangement does not produce correlation.

A good PRNG in this arrangement would have small state (because one will be instantiated in each of a massive number of threads) and O(1) access to the nth state in the sequence (because each thread needs to "jump" to state n to avoid colliding with the states consumed by other threads). The D.E. Shaw Research stuff I linked to in my last comment is designed in this way.

**Closed** 2023-03-07 03:37 UTC
Labels: type: enhancement, info needed, thrust
