### ISSUE TITLE
Custom memory resource/allocator is not used by `thrust::async` algorithms for temporary allocations

### ISSUE THREAD

**Issue by pauleonix** [NVIDIA/thrust#1718] opened 2022-06-11 04:06 UTC
I'm trying to implement a multi-buffered sort (i.e. overlapping h2d copy, sort of a sub-range and d2h copy in three different streams) using the `async` API. For this I would like to use a custom memory resource (inspired by the `cached_allocator` from the examples, but always giving a pointer to the same block when asked for the same size, one resource per stream) to avoid the unnecessary allocations for temporary storage in `thrust::async::sort`. When using the `thrust::device(alloc).after(h2d)` execution policy, my allocator (I tried both `thrust::mr::allocator` and `thrust::mr::polymorphic_allocator` with the adaptor resource as in `mr_basic.cu`) seems to get ignored as debug print statements inside the resource are not executed and I can see the many calls to `cudaMalloc` in the `nsys` profile.

Are custom allocators for `async` algorithms always ignored? Or does my allocator/memory resource just need to fulfill some requirement to be used? When used for a `thrust::device_vector` it seems to work fine.

**Comment by pauleonix** [comment] 2022-06-11 05:40
```c++
#include <thrust/memory.h>
#include <thrust/mr/memory_resource.h>

#include <algorithm>
#include <cstdlib>
#ifndef NDEBUG
#include <iostream>
#endif
#include <sstream>
#include <string>
#include <tuple>
#include <vector>

struct not_my_pointer {
    not_my_pointer(void* p) : message() {
        std::stringstream s;
        s << "Pointer `" << p << "` was not allocated by this allocator.";
        message = s.str();
    }

    virtual ~not_my_pointer() {}

    virtual const char* what() const { return message.c_str(); }

   private:
    std::string message;
};

template <class Upstream>
class unsafe_cached_resource final
    : public thrust::mr::memory_resource<typename Upstream::pointer> {
   public:
    unsafe_cached_resource(Upstream* upstream) : m_upstream(upstream) {}

    unsafe_cached_resource()
        : m_upstream(thrust::mr::get_global_resource<Upstream>()) {}

    ~unsafe_cached_resource() { release(); }

   private:
    typedef typename Upstream::pointer void_ptr;
    typedef std::tuple<std::ptrdiff_t, std::size_t, void_ptr> block_t;
    std::vector<block_t> blocks{};
    Upstream* m_upstream;

   public:
    void release() {
#ifndef NDEBUG
        std::cout << "unsafe_cached_resource::release()" << std::endl;
#endif
        std::for_each(blocks.begin(), blocks.end(), [this](block_t& block) {
            auto& [bytes, alignment, ptr] = block;
            m_upstream->do_deallocate(ptr, bytes, alignment);
        });
    }

    void_ptr do_allocate(std::size_t bytes, std::size_t alignment) override {
#ifndef NDEBUG
        std::cout << "unsafe_cached_resource::do_allocate(): num_bytes == "
                  << bytes << std::endl;
#endif
        void_ptr result = nullptr;

        auto const fitting_block = std::find_if(
            blocks.cbegin(), blocks.cend(),
            [bytes, alignment](block_t const& block) {
                auto& [b_bytes, b_alignment, _] = block;
                return b_bytes == bytes && b_alignment == alignment;
            });

        if (fitting_block != blocks.end()) {
#ifndef NDEBUG
            std::cout
                << "unsafe_cached_resource::do_allocate(): found a free block"
                << std::endl;
#endif
            result = std::get<2>(*fitting_block);
        } else {
#ifndef NDEBUG
            std::cout
                << "unsafe_cached_resource::do_allocate(): allocating new block"
                << std::endl;
#endif
            result = m_upstream->do_allocate(bytes, alignment);
            blocks.emplace_back(bytes, alignment, result);
        }
        return result;
    }

    void do_deallocate(void_ptr ptr, std::size_t bytes,
                       std::size_t alignment) override {
#ifndef NDEBUG
        std::cout << "single_block_cached_allocator::do_deallocate(): ptr == "
                  << reinterpret_cast<void*>(ptr.get()) << std::endl;
#endif
        auto const fitting_block = std::find_if(
            blocks.cbegin(), blocks.cend(),
            [ptr](block_t const& block) { return std::get<2>(block) == ptr; });

        if (fitting_block == blocks.end()) {
            throw not_my_pointer(thrust::raw_pointer_cast(ptr));
        }
    }
};
```

**Comment by allisonvacanti** [comment] 2022-06-22 19:45
This sounds like the same root cause as #1195. Since the [async algorithms are no longer actively developed](https://github.com/NVIDIA/thrust/issues/961#issuecomment-1163525229) it's unlikely that this will get fixed in the current `thrust::async` interfaces. We're working on an alternative async API that would avoid these issues, but this is still in the early stages of development.

**Comment by allisonvacanti** [comment] 2023-02-23 16:17
The Thrust async algorithms are not going to be supported going forward, prefer to use the `thrust::cuda::par_nosync` execution policy where supported instead.

**Closed by allisonvacanti** 2023-02-23 16:17 UTC
Labels: type: bug: functional, P3: backlog, thrust
