### ISSUE TITLE
Construction of host_vector incorrectly dispatches to CUB version of uninitialized_copy_n under certain circumstances.

### ISSUE THREAD

**Issue by nvdbaranec** [NVIDIA/thrust#1385] opened 2021-02-13 00:08 UTC
With the following code, we would expect thrust to end up dispatching to host-side code, but it ends up attempting to launch the cub version of `thrust::uninitialized_copy_n`.   

```
#include <thrust/device_vector.h>
struct identity {
  template <typename T>
    T operator()(T x){ 
      return x;  
    }
};
int main(void){
  thrust::device_vector<int> d_v(10);
  auto transformer = thrust::make_transform_iterator(d_v.begin(), identity{} );
  thrust::host_vector<int> hh_v(transformer, transformer + d_v.size());    
  assert(cudaSuccess == cudaDeviceSynchronize());
}
```

This ends up ultimately failing with:

```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  uninitialized_copy_n: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure
```

**Comment by jrhemstad** [comment] 2021-02-13 00:14
@allisonvacanti this seems like a bug in the dispatch logic? Or maybe unfortunate expected behavior? I'm guessing that when the `thrust::host_vector(device_vector)` ctor calls `uninitialized_copy_n`, it sees the the iterator is a device iterator and dispatches to the `cuda::cub` version. Note that when you eliminate the `transform_iterator` from the mix, it works fine:
```
#include <thrust/device_vector.h>

int main(void){
  thrust::device_vector<int> d_v(10);

  thrust::host_vector<int> hh_v(d_v.begin(),d_v.end());    

  assert(cudaSuccess == cudaDeviceSynchronize());
}
```

**Comment by griwes** [comment] 2021-02-13 00:28
Does the original snippet work when you qualify the call operator of identity with as host/device?

**Comment by allisonvacanti** [comment] 2021-02-16 17:41
I'm not aware of a way to control where the initialization happens in this constructor. I don't think it's defined behavior -- the docs don't say anything about it, anyway.

I don't think this is a bug. My understanding is that the copy can happen on either host or device when the inputs are heterogeneous. Why would using a device-side `uninitialized_copy_n` for cross-system copies be incorrect? The current behavior is what I'd expect, using device execution for cross-system copies is generally going to give better performance.

Agreed with @griwes, the error is probably because the functor doesn't have `__device__` qualifications.

You may have to explicitly use a copy algorithm with a host execution_policy to get the behavior you want here. Would that work for your usecase?

**Comment by jrhemstad** [comment] 2021-02-16 18:22
> Why would using a device-side uninitialized_copy_n for cross-system copies be incorrect?

In my mind, since it's ultimately a device-to-host memcpy, there isn't a way to do that device-side since kernels cant touch host memory (unless the host memory is pinned/unified, which it's not here).

**Comment by allisonvacanti** [comment] 2021-02-16 19:06
> Or did this compile because Thrust uses nv_exec_check_disable?

Probably, it would make sense here.

> In my mind, since it's ultimately a device-to-host memcpy, there isn't a way to do that device-side since kernels cant touch host memory (unless the host memory is pinned/unified, which it's not here).

It's more than a memcpy because of the `transform_iterator`. It sounds like thrust is transforming the inputs into a temporary buffer on the device and then transferring the transformed results to the host. Is that reasonable for what you're trying to do, or do you require the transform to run in serial on the host?

**Comment by jrhemstad** [comment] 2021-02-16 19:19
> It sounds like thrust is transforming the inputs into a temporary buffer on the device and then transferring the transformed results to the host. Is that reasonable for what you're trying to do, or do you require the transform to run in serial on the host?

Yeah, that's totally reasonable.

We saw a failure in some similar code and I was worried that Thrust launching a kernel that was attempting to write to host memory directly. I didn't think about the `device` decorators since I would have thought it would fail to compile if that was the issue, but disabling the execution space check silenced it. 

So my understanding is satisfied now. I think this issue can be closed.

**Comment by allisonvacanti** [comment] 2021-02-16 20:42
Gotcha, that's understandable. That diagnostic is horrible, there's nothing less helpful than "unspecified launch failure" :)

I'll close this out. For completeness, if a transform functor cannot run on the device for whatever reasons, something like:

```
  thrust::device_vector<int> d_v(10);
  thrust::host_vector<int> h_tmp(d_v); // explicit copy to host
  auto transformer = thrust::make_transform_iterator(h_tmp.begin(), identity{} );
  thrust::host_vector<int> hh_v(transformer, transformer + h_tmp.size());
```

ought to work.

**Closed by allisonvacanti** 2021-02-16 20:42 UTC
