### ISSUE TITLE
Unexpected errors in thrust headers

### ISSUE THREAD

**Issue by nikita-astronaut** [NVIDIA/thrust#979] opened 2019-04-28 08:09 UTC
Dear all, I am compiling my program with NVCC release 9.1, V9.1.85 and using the thrust reduce operation. I get the following errors in the header files of thrust and the code does not compile. Has anyone seen this error before?

`/opt/cuda/include/thrust/iterator/constant_iterator.h(220): error: a class or namespace qualified name is required

/opt/cuda/include/thrust/iterator/constant_iterator.h(220): error: expected a ")"

/opt/cuda/include/thrust/iterator/constant_iterator.h(220): error: expected a type specifier

/opt/cuda/include/thrust/iterator/constant_iterator.h(222): error: expected a ")"

/opt/cuda/include/thrust/iterator/constant_iterator.h(222): error: expected a type specifier

/opt/cuda/include/thrust/iterator/constant_iterator.h(222): error: expected a ")"

/opt/cuda/include/thrust/iterator/constant_iterator.h(222): error: expected a type specifier

/opt/cuda/include/thrust/iterator/constant_iterator.h(222): error: expected a ";"`

**Comment by griwes** [comment] 2019-04-28 15:19
Please share a code example that produces these error messages.

**Comment by svarshini** [comment] 2019-09-09 11:07
I ran into something similar today. After spending some time debugging, I found a temporary solution but I believe this is a bug that needs to be fixed. I use CUDA 10.1. My error looked like this:

/usr/local/cuda-10.1/include/thrust/detail/integer_math.h(97): error: expected a ")"

/usr/local/cuda-10.1/include/thrust/detail/integer_math.h(97): error: expected a ")"

/usr/local/cuda-10.1/include/thrust/detail/integer_math.h(97): error: expected a ")"

/usr/local/cuda-10.1/include/thrust/detail/integer_math.h(97): error: template parameter "Integer0" may not be redeclared in this scope

/usr/local/cuda-10.1/include/thrust/detail/integer_math.h(94): error: attribute "__host__" does not apply here

/usr/local/cuda-10.1/include/thrust/detail/integer_math.h(94): warning: attribute "always_inline" does not apply here

/usr/local/cuda-10.1/include/thrust/detail/integer_math.h(97): error: cannot deduce "auto" type (initializer required)

/usr/local/cuda-10.1/include/thrust/detail/integer_math.h(98): error: expected a ";"

/usr/local/cuda-10.1/include/thrust/detail/integer_math.h(148): warning: parsing restarts here after previous syntax error

Initially, I believed it to be an issue with my CMakeLists.txt but finally, it turned out to be the order in which I was including the CUDA and Thrust header files in my .cu file. The order that caused an issue was:

#include "cutil.h"
#include<iostream>
#include<stdio.h>
#include<cuda_runtime.h>
#include<fstream>
#include<thrust/host_vector.h>
#include<thrust/device_vector.h>
#include<thrust/scan.h>

After changing this order and including the Thrust files at the top, my issue got fixed. 
#include<thrust/host_vector.h>
#include<thrust/device_vector.h>
#include<thrust/scan.h>
#include "cutil.h"
#include<iostream>
#include<stdio.h>
#include<cuda_runtime.h>
#include<fstream>

**Comment by allisonvacanti** [comment] 2021-01-26 21:50
Some of those headers are problematic. "cutil.h" hasn't been distributed with the CUDA toolkit for many releases, and some of the headers aren't valid (iostream.h, fstream.h).

I can't reproduce this after removing the `cutil.h` and changing the stream headers to the standard spellings: https://www.godbolt.org/z/vhhMv8

I suspect the issue is somewhere in the version of cutil.h that's getting pulled in, but I'm not sure where it's coming from or what would be conflicting.

Closing since this seems out of scope for Thrust. Feel free to reopen if you have a portable reproduction.

**Closed by allisonvacanti** 2021-01-26 21:50 UTC
