### ISSUE TITLE
[BUG] Host vector to device vector `operator=` fails with CUDA 10 on CentOS 7

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/thrust#956] opened 2019-02-26 20:27 UTC
I uncovered a compile-time error when invoking `operator=` trying to copy a host vector to a device vector when `T` is a non-fundamental type without a default constructor.

Matrix of attempted versions:

Ubuntu 16.04 + CUDA 9.2 = works
Ubuntu 16.04 + CUDA 10 = works
Ubuntu 18.04 + CUDA 9.2 = works
Ubuntu 18.04 + CUDA 10 = works
CentOS 7 + CUDA 9.2 = works
CentOS 7 + CUDA 10 = failure

Minimal reproducer:

```
// compile with nvcc --std=c++11 ./test.cu
#include <thrust/device_vector.h>
#include <thrust/host_vector.h>

struct foo {
  //foo() = default; // This code will fail to compile on CentOS7 + CUDA10 without a default ctor
  foo(int n) : value{n} { }
  int value;
};

thrust::host_vector<foo> return_vector(){
  thrust::host_vector<foo> h_vec;
  h_vec.push_back(foo{0});
  return h_vec;
}

int main(void){
  thrust::device_vector<foo> d_vec = return_vector();
}
```

The error I get at compile time is:

```
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/allocator/allocator_traits.inl(92): error: no instance of constructor "foo::foo" matches the argument list
          detected during:
            instantiation of "thrust::detail::disable_if<thrust::detail::allocator_traits_detail::has_member_construct1<Alloc, T>::value, void>::type thrust::detail::allocator_traits_detail::construct(Alloc &, T *) [with Alloc=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<foo, thrust::system::cpp::detail::tag>>, T=foo]" 
(270): here
            instantiation of "void thrust::detail::allocator_traits<Alloc>::construct(thrust::detail::allocator_traits<Alloc>::allocator_type &, T *) [with Alloc=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<foo, thrust::system::cpp::detail::tag>>, T=foo]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/allocator/default_construct_range.inl(46): here
            instantiation of "void thrust::detail::allocator_traits_detail::construct1_via_allocator<Allocator>::operator()(T &) [with Allocator=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<foo, thrust::system::cpp::detail::tag>>, T=foo]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/function.h(60): here
            instantiation of "Result thrust::detail::wrapped_function<Function, Result>::operator()(const Argument &) const [with Function=thrust::detail::allocator_traits_detail::construct1_via_allocator<thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<foo, thrust::system::cpp::detail::tag>>>, Result=void, Argument=thrust::reference<foo, thrust::pointer<foo, thrust::system::cpp::detail::tag, thrust::use_default, thrust::use_default>, thrust::use_default>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/detail/sequential/for_each.h(83): here
            instantiation of "InputIterator thrust::system::detail::sequential::for_each_n(thrust::system::detail::sequential::execution_policy<DerivedPolicy> &, InputIterator, Size, UnaryFunction) [with DerivedPolicy=thrust::system::cpp::detail::tag, InputIterator=thrust::pointer<foo, thrust::system::cpp::detail::tag, thrust::use_default, thrust::use_default>, Size=std::size_t, UnaryFunction=thrust::detail::allocator_traits_detail::construct1_via_allocator<thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<foo, thrust::system::cpp::detail::tag>>>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/for_each.inl(71): here
            [ 16 instantiation contexts not shown ]
            instantiation of "void thrust::detail::vector_base<T, Alloc>::allocate_and_copy(thrust::detail::vector_base<T, Alloc>::size_type, ForwardIterator, ForwardIterator, thrust::detail::vector_base<T, Alloc>::storage_type &) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, ForwardIterator=thrust::detail::normal_iterator<const foo *>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/vector_base.inl(230): here
            instantiation of "void thrust::detail::vector_base<T, Alloc>::range_init(ForwardIterator, ForwardIterator, thrust::random_access_traversal_tag) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, ForwardIterator=thrust::detail::normal_iterator<const foo *>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/vector_base.inl(207): here
            instantiation of "void thrust::detail::vector_base<T, Alloc>::range_init(InputIterator, InputIterator) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, InputIterator=thrust::detail::normal_iterator<const foo *>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/vector_base.inl(119): here
            instantiation of "thrust::detail::vector_base<T, Alloc>::vector_base(const thrust::detail::vector_base<OtherT, OtherAlloc> &) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, OtherT=foo, OtherAlloc=std::allocator<foo>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/device_vector.inl(33): here
            instantiation of "thrust::device_vector<T, Alloc>::device_vector(const thrust::host_vector<OtherT, OtherAlloc> &) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, OtherT=foo, OtherAlloc=std::allocator<foo>]" 
test.cu(18): here

/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/allocator/allocator_traits.inl(92): error: no instance of constructor "foo::foo" matches the argument list
          detected during:
            instantiation of "thrust::detail::disable_if<thrust::detail::allocator_traits_detail::has_member_construct1<Alloc, T>::value, void>::type thrust::detail::allocator_traits_detail::construct(Alloc &, T *) [with Alloc=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<foo, thrust::cuda_cub::tag>>, T=foo]" 
(270): here
            instantiation of "void thrust::detail::allocator_traits<Alloc>::construct(thrust::detail::allocator_traits<Alloc>::allocator_type &, T *) [with Alloc=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<foo, thrust::cuda_cub::tag>>, T=foo]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/allocator/default_construct_range.inl(46): here
            instantiation of "void thrust::detail::allocator_traits_detail::construct1_via_allocator<Allocator>::operator()(T &) [with Allocator=thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<foo, thrust::cuda_cub::tag>>, T=foo]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/function.h(51): here
            instantiation of "Result thrust::detail::wrapped_function<Function, Result>::operator()(Argument &) const [with Function=thrust::detail::allocator_traits_detail::construct1_via_allocator<thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<foo, thrust::cuda_cub::tag>>>, Result=void, Argument=foo]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/for_each.h(57): here
            instantiation of "void thrust::cuda_cub::for_each_f<Input, UnaryOp>::operator()(Size) [with Input=thrust::pointer<foo, thrust::cuda_cub::tag, thrust::use_default, thrust::use_default>, UnaryOp=thrust::detail::wrapped_function<thrust::detail::allocator_traits_detail::construct1_via_allocator<thrust::detail::no_throw_allocator<thrust::detail::temporary_allocator<foo, thrust::cuda_cub::tag>>>, void>, Size=unsigned long]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/parallel_for.h(98): here
            [ 24 instantiation contexts not shown ]
            instantiation of "void thrust::detail::vector_base<T, Alloc>::allocate_and_copy(thrust::detail::vector_base<T, Alloc>::size_type, ForwardIterator, ForwardIterator, thrust::detail::vector_base<T, Alloc>::storage_type &) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, ForwardIterator=thrust::detail::normal_iterator<const foo *>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/vector_base.inl(230): here
            instantiation of "void thrust::detail::vector_base<T, Alloc>::range_init(ForwardIterator, ForwardIterator, thrust::random_access_traversal_tag) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, ForwardIterator=thrust::detail::normal_iterator<const foo *>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/vector_base.inl(207): here
            instantiation of "void thrust::detail::vector_base<T, Alloc>::range_init(InputIterator, InputIterator) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, InputIterator=thrust::detail::normal_iterator<const foo *>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/vector_base.inl(119): here
            instantiation of "thrust::detail::vector_base<T, Alloc>::vector_base(const thrust::detail::vector_base<OtherT, OtherAlloc> &) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, OtherT=foo, OtherAlloc=std::allocator<foo>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/device_vector.inl(33): here
            instantiation of "thrust::device_vector<T, Alloc>::device_vector(const thrust::host_vector<OtherT, OtherAlloc> &) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, OtherT=foo, OtherAlloc=std::allocator<foo>]" 
test.cu(18): here

/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/get_value.h(48): error: no default constructor exists for class "foo"
          detected during:
            instantiation of "thrust::iterator_value<Pointer>::type thrust::cuda_cub::<unnamed>::get_value_msvc2005_war(thrust::cuda_cub::execution_policy<DerivedPolicy> &, Pointer) [with DerivedPolicy=thrust::cuda_cub::tag, Pointer=thrust::pointer<foo, thrust::cuda_cub::tag, thrust::use_default, thrust::use_default>]" 
(80): here
            instantiation of "thrust::iterator_value<Pointer>::type thrust::cuda_cub::get_value(thrust::cuda_cub::execution_policy<DerivedPolicy> &, Pointer) [with DerivedPolicy=thrust::cuda_cub::tag, Pointer=thrust::pointer<foo, thrust::cuda_cub::tag, thrust::use_default, thrust::use_default>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/reference.inl(137): here
            instantiation of "thrust::reference<Element, Pointer, Derived>::value_type thrust::reference<Element, Pointer, Derived>::strip_const_get_value(const System &) const [with Element=foo, Pointer=thrust::pointer<foo, thrust::cuda_cub::tag, thrust::use_default, thrust::use_default>, Derived=thrust::use_default, System=thrust::cuda_cub::tag]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/reference.inl(105): here
            instantiation of "thrust::reference<Element, Pointer, Derived>::value_type thrust::reference<Element, Pointer, Derived>::convert_to_value_type(System *) const [with Element=foo, Pointer=thrust::pointer<foo, thrust::cuda_cub::tag, thrust::use_default, thrust::use_default>, Derived=thrust::use_default, System=thrust::device_system_tag]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/reference.inl(122): here
            instantiation of "thrust::reference<Element, Pointer, Derived>::operator thrust::reference<Element, Pointer, Derived>::value_type() const [with Element=foo, Pointer=thrust::pointer<foo, thrust::cuda_cub::tag, thrust::use_default, thrust::use_default>, Derived=thrust::use_default]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/system/detail/sequential/general_copy.h(76): here
            [ 16 instantiation contexts not shown ]
            instantiation of "void thrust::detail::vector_base<T, Alloc>::allocate_and_copy(thrust::detail::vector_base<T, Alloc>::size_type, ForwardIterator, ForwardIterator, thrust::detail::vector_base<T, Alloc>::storage_type &) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, ForwardIterator=thrust::detail::normal_iterator<const foo *>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/vector_base.inl(230): here
            instantiation of "void thrust::detail::vector_base<T, Alloc>::range_init(ForwardIterator, ForwardIterator, thrust::random_access_traversal_tag) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, ForwardIterator=thrust::detail::normal_iterator<const foo *>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/vector_base.inl(207): here
            instantiation of "void thrust::detail::vector_base<T, Alloc>::range_init(InputIterator, InputIterator) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, InputIterator=thrust::detail::normal_iterator<const foo *>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/vector_base.inl(119): here
            instantiation of "thrust::detail::vector_base<T, Alloc>::vector_base(const thrust::detail::vector_base<OtherT, OtherAlloc> &) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, OtherT=foo, OtherAlloc=std::allocator<foo>]" 
/usr/local/cuda/bin/../targets/x86_64-linux/include/thrust/detail/device_vector.inl(33): here
            instantiation of "thrust::device_vector<T, Alloc>::device_vector(const thrust::host_vector<OtherT, OtherAlloc> &) [with T=foo, Alloc=thrust::device_malloc_allocator<foo>, OtherT=foo, OtherAlloc=std::allocator<foo>]" 
test.cu(18): here

3 errors detected in the compilation of "/tmp/tmpxft_00000092_00000000-8_test.cpp1.ii".
```

Related https://github.com/rapidsai/cudf/pull/1054

**Comment by codecircuit** [comment] 2019-04-17 10:12
I checked:

- CentOS7, gcc@7.3.0, cuda@10.0.130 = works
- CentOS7, gcc@8.3.0, cuda@10.1.105 = works
- CentOS7, gcc@4.8.5, cuda@10.0.130 = works
- CentOS7, gcc@6.4.0, cuda@10.0.130 = works

What else can be the issue here?

**Comment by jrhemstad** [comment] 2019-04-17 14:47
@mike-wendt or @rlratzel do you recall what exact version of CUDA10 and gcc caused the failure we saw that was resolved here: https://github.com/rapidsai/cudf/pull/1054 ?

**Comment by jaredhoberock** [comment] 2019-04-17 15:04
Here is the function in question:

```
    __host__ inline static result_type host_path(execution_policy<DerivedPolicy> &exec, Pointer ptr)
    {
      // when called from host code, implement with assign_value
      // note that this requires a type with default constructor
      result_type result;

      thrust::host_system_tag host_tag;
      cross_system<thrust::host_system_tag, DerivedPolicy> systems(host_tag, exec);
      assign_value(systems, &result, ptr);

      return result;
    }
```

If `assign_value` could do a placement new, then `result` could `std::aligned_storage<result_type>` or something. However, I'm pretty sure `assign_value` just does an assignment.

**Comment by rlratzel** [comment] 2019-04-24 21:39
I can see the error in question using Jake's minimal reproducer with the following:
```
(rapids) [root@085681041c88 tmp]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

(rapids) [root@085681041c88 tmp]# gcc --version
gcc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(rapids) [root@085681041c88 tmp]# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```
I also have a CentOS Docker image you can use to reproduce the problem, if that helps.
I should also mention that the gcc used here was built on that CentOS system from source (as opposed to using something like `devtoolset-7`) in order to generate binaries with the new ABI.

**Comment by griwes** [comment] 2019-04-24 21:55
Do share the image, I'll see whether I can figure out what's going on.

**Comment by rlratzel** [comment] 2019-04-24 22:33
> Do share the image, I'll see whether I can figure out what's going on.

Here's what I used to reproduce it, note the `gcc` path:
```
rratzel@sm10:~$ nvidia-docker run -ti --rm --cap-add=SYS_PTRACE rapidsai/rapidsai-nightly:cuda10.0-devel-centos7 bash
(rapids) bash-4.2# which gcc
/rapids/gcc7/bin/gcc
```

**Comment by rlratzel** [comment] 2019-07-26 17:19
@griwes were you able to make any progress on this?

**Comment by miscco** [comment] 2023-02-24 10:43
I am closing this because it has been quite a while and we do not support CUDA10 anymore

**Closed by miscco** 2023-02-24 10:43 UTC
Labels: thrust
